---
  - name: Add tomcat group
    group:
      name: tomcat

  - name: Add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no

  - name: Create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: Download Tomcat & unarchive
    unarchive:
      src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.36/bin/apache-tomcat-9.0.36.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change tomcat folder ownership
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: yes
      daemon_reload: yes